### PR TITLE
Revert "Generic connection compat"

### PR DESCRIPTION
**Pull request by aleshaleksey**
Reverts GiGainfosystems/diesel#3
Some kind of compatibility problem. God knows.

### CODE REVIEW

**Comment by weiznich** [comment]
I would really like to here some details here. Please try to give at least some context what "Some kind of compatibility problem. God knows." means, otherwise I'm not able to review this.

**Comment by weiznich** [comment]
Additionally I do not see how this would solve whatever "compatibility problem" in the long term, as this is already merged into diesel, so the next diesel update needs to handle that anyway. From that point of view: Better handle it now/fix it on diesel side instead of just revert this change.

**Comment by aleshaleksey** [comment]
It sounds like a joke, but I changed the URL of the repoository on GST and it stopped building, despite the code all being the same. I will have to fiddle about until everything works.

In all likelihood there is nothing wrong with this particular commit. Per se. 

I have said as much as I know. Maybe it does not need to be rolled back. If I find out the exact cause I will explain it here. More likely our dependency chain has become so tangled that simply changing the url of the repository in the Cargo.toml of GST means that it stops compiling. Maybe cancel this, maybe don't.

**Comment by aleshaleksey** [comment]
So basically when I use this version, for whatever reason cargo insists on using an older version of `serde_json`.
Therefore it is probably not related to this, so you guys can close it if you want. I'll beat Cargo over the head with a dead horse until it stops being silly, or until I figure out what is going on and come up with a clever solution, or until the heat death of the universe, whichever comes first.

**Comment by weiznich** [comment]
Closed as the "compatibility problems" are caused by something different. Use `cargo update -p serde_json:0.9.x --precise 1.0.y` to fix them.

**Pull request closed without merging**
